name: Deploy to Vercel

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: pnpm run build

      - name: Deploy to Vercel
        id: vercel-deploy
        run: |
          if [ "${{ github.ref_name }}" = "main" ]; then
            echo "🚀 Deploying to Production..."
            pnpx vercel --prod --confirm --token ${{ secrets.VERCEL_TOKEN }}
          else
            echo "🧪 Deploying to Preview..."
            PREVIEW_URL=$(pnpx vercel --confirm --token ${{ secrets.VERCEL_TOKEN }} | tail -n1)
            echo "preview_url=$PREVIEW_URL" >> $GITHUB_OUTPUT
          fi

      - name: Comment on PR with Preview URL
        if: github.event_name == 'pull_request' && github.ref_name != 'main'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr comment ${{ github.event.pull_request.number }} \
            --body "✅ Preview ready: ${{ steps.vercel-deploy.outputs.preview_url }}"